### ISSUE TITLE
Unauthorization errors when invoking lambda

### ISSUE THREAD

**Issue by vin4git** [joseph-holland/lambda-graffiti-monkey#1]
Hi Joseph,

Its nice to see this implementation using lambda. Unfortunately I'm facing issues during the lambda invocation step. I have cross-checked the IAM permissions for me and it looks good. Below are the error details and kindly help to fix this issue:

$ lambda invoke -v
INFO:service:Loading function
INFO:graffiti_monkey.core:Connecting to region us-west-2 using profile None
INFO:graffiti_monkey.core:Getting list of all volumes
ERROR:boto:403 Forbidden
ERROR:boto:<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>648f83a9-94c0-44ad-80eb-940a413b41f6</RequestID></Response>
ERROR:service:Error: Graffiti Monkey encountered the following error: EC2ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>648f83a9-94c0-44ad-80eb-940a413b41f6</RequestID></Response>
None

execution time: 1.88420010s
function execution timeout: 15s
(graffiti-monkey)

Thanks.

**Comment by joseph-holland** [comment]
Hi, 

The local python-lamdba execution (lambda invoke) does not actually use the IAM role. It uses you the awscli credentials. 

I see from the log output that it's not picked up an awscli profile (using profile none). 

Can you ensure that the awscli is installed and working. "aws s3 ls" for example should list all s3 buckets you have setup. The awscli is pretty easy to install and setup: http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

I will update the README to include this info and will update requirements.txt to also include the awscli. 

Joe

**Comment by vin4git** [comment]
Hello Joseph,

AWS CLI is working properly (I checked by running the cli commands). I believe that showing the profile as None is not an issue here.  Could you please share the zip file created by your lambda function? In that way, I can test directly in the aws console by uploading the code. 

Thanks.

**Comment by joseph-holland** [comment]
I've published a release with the Lambda deployment package [here](https://github.com/joseph-holland/lambda-graffiti-monkey/releases/tag/0.1).

Let me know if it works for you.

**Comment by vin4git** [comment]
Hello Joseph,

Thanks for sharing this deployment package !!!

I tried creating the lambda function by uploading this package but it is failing with "errorMessage": "Unable to import module 'lambda_function'".  I just went with the default lambda function handler name (lambda_function.lambda_handler).  Looks like we need to provide the main python file name in handler name of lambda function (like: Python_File_Name.Method_Name). I'm unable to find it out in the deployment package. Could you please help?

**Comment by joseph-holland** [comment]
The Lambda handler to use is:
`service.handler`

This entry point can be found within the service.py file.

**Comment by joseph-holland** [comment]
I've updated the [release docs](https://github.com/joseph-holland/lambda-graffiti-monkey/releases/tag/0.1) to include this info.  I plan to update the README soon also.

**Comment by vin4git** [comment]
Thanks Joseph.  I found it out (an hour ago) and tried with the same name and it worked. But now, it is throwing "Error Message: Task timed out after 3.00 seconds". There is no clue about the errors on the same in CloudWatch ::(

**Comment by joseph-holland** [comment]
Apologies.  In the Lambda function's settings under **Configuration** -> **Advanced**, ensure that the **Timeout** is set to **5** minutes.

It should work then!

**Comment by vin4git** [comment]
My bad. :( Its working now. Appreciate your support !!!

**Comment by joseph-holland** [comment]
Cool.  Glad you got it working.  I'll close this off so and update the docs when I get the chance.
