### ISSUE TITLE
SNS is working only when lambda function completes successfully

### ISSUE THREAD

**Issue by vin4git** [joseph-holland/lambda-graffiti-monkey#11]
@joseph-holland - This is not working when lambda function execution is failed (SNS Notification is not triggered). It is working as expected when function completes successfully (SNS Notification triggered).

I just changed the handler to make it failed but no notification triggered. As per the new code, it should trigger when failed/succeed. Please look into this issue. Thanks

**Comment by joseph-holland** [comment]
I missed this notification.

If the handler name is changed the Lambda function does not have an entry point into the Python code.  If this happens the error handling does not work as none of the Python code is actually ran, this is more a fundamental issue with Lambda, than a problem with the code itself.
