### ISSUE TITLE
filter option not working

### ISSUE THREAD

**Issue by ghost** [joseph-holland/lambda-graffiti-monkey#12]
Hi Guys,

I am trying to use filter option for one particular instance or tag value buts not working. Can anyone help me on this please. want to test on one instance first in PROD before implementing in entire environment.

**Comment by joseph-holland** [comment]
Hi @vishalbaghla ,
Apologies for not coming back to you sooner.  What's happening with the filter option?  You say you've tried tags and instance ids.

See more info in [graffiti_monkey source](https://github.com/Answers4AWS/graffiti-monkey/commit/b560d408d136bd1921606997dcd6191aec5bd358#diff-56fc4d08e8d7ff162089c2ed4337eed4):
```_instance_filter:
# Filter values with the same key (eg, tag:app) are an OR
# Different filter keys are an AND operation (eg, tag:app and tag:team)
# See the Filter section in http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstances.html#API_DescribeInstances_RequestParameters
# Example entries:
#    'tag:app':   ['app1', 'app2']
#    'tag:team': 'team1'
```

-Joe

**Comment by joseph-holland** [comment]
I've also thought of something that should assist you.  Graffiti Monkey supports running in dry run mode where it will not make any changes, but only output what it _would_ have done if ran fully.

I can implement a new feature to allow a DRY_RUN environment variable to be specified.  Defaults to false, but can be to true to only test the function.

How does this sound?
