### ISSUE TITLE
Multi-region support

### ISSUE THREAD

**Issue by vin4git** [joseph-holland/lambda-graffiti-monkey#4]
Hi Joseph,

Looks like this works only for one region at a time in an account. 

Thanks.

**Comment by joseph-holland** [comment]
Hi @vin4git ,

You should be able to run the function against a different region by setting the REGION environment variable to the other region.

The only drawback to doing it this way is if you require Graffiti Monkey to be ran against multiple regions you would need to create separate functions for each region and then specify the different REGION environment variable for each.  Does this make sense?  

For example you could have 3 Lambda Graffiti Monkey function deployed to eu-west-1, running against eu-west-1, us-east-1 and us-west-2.

I _may_ add real multi-region support in the future where the REGION environment variable could accept multiple values and then Graffiti Monkey could be run against each, _but_ (big but here) then I suspect we may hit issues with the Lambda max running time of 5 minutes.  So a separate function per region may actually be better.  Also probably better for logging and debugging this way too.  Lambda can be a pain with that so separating each region per function is probably best.

Question, opinions??  Let me know if you get it working anyway.

Joe

**Comment by vin4git** [comment]
Hello Joseph,

I completely agree with your points. Regarding the opinions, I wish it would be good to include a code related to SNS so whenever the lambda triggers (by scheduled cloudwatch events) it should sent a notification to users on that (Might be there should be one environment variable to put the SNS Topic ARN).

Thanks.

**Comment by joseph-holland** [comment]
Thanks for your feedback. I'll look at adding notifications to the application work flow. 

Did you get a chance to test the multi region setup with multiple functions? Any issues?

**Comment by vin4git** [comment]
Yes it is working great !!! 😃

**Comment by joseph-holland** [comment]
Hi @vin4git ,
I've created a [Kanban board](https://github.com/joseph-holland/lambda-graffiti-monkey/projects/1) to track development work on this project and added you SNS suggestion to the backlog.
Thanks!
