### ISSUE TITLE
Add notification functionality via SNS

### ISSUE THREAD

**Issue by joseph-holland** [joseph-holland/lambda-graffiti-monkey#6]

**Comment by joseph-holland** [comment]
@vin4git - I've added SNS notification functionality now.  Would you mind testing it?

You need to also set the following Lambda environment variable - SNS_ARN.  You will need to have this created in advance and be subscribed to the topic.

You can test by removing one of the other env vars such as VOLUME_TAGS_TO_PROPAGATE and testing the function.

Let me know how it goes if you have a chance to test it.

Thanks!

**Comment by joseph-holland** [comment]
Updated release with new Lambda deployment package: https://github.com/joseph-holland/lambda-graffiti-monkey/releases/tag/0.2

**Comment by vin4git** [comment]
Sorry Joseph for a very late response. I have tried with the updated package. SNS functionality is working fine only when lambda function execution fails with some errors. But usually we should get notified in both cases (success/failure) assuming we schedule the lambda function to run on daily/weekly basis.
