### ISSUE TITLE
SNS should work when function completes success/failure

### ISSUE THREAD

**Issue by vin4git** [joseph-holland/lambda-graffiti-monkey#9]
SNS functionality is working fine only when lambda function execution fails with some errors. But usually we should get notified in both cases (success/failure) assuming we schedule the lambda function to run on daily/weekly basis.

**Comment by joseph-holland** [comment]
I plan to look at this issue this week.

**Comment by joseph-holland** [comment]
I've now updated the code to send notifications on both error and success.

**Comment by joseph-holland** [comment]
New draft release 0.3 with this feature: https://github.com/joseph-holland/lambda-graffiti-monkey/releases/tag/0.3

**Comment by vin4git** [comment]
@joseph-holland - This is not working when lambda function execution is failed (SNS Notification is not triggered). It is working as expected when function completes successfully (SNS Notification triggered).

I just changed the handler to make it failed but no notification triggered. Please look into it. Thanks
